<?php

namespace Database\Seeders;

use App\Models\NilaiBobotKriteria;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NilaiBobotKriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $nilai_bobot_kriterias = array(
            array(
                "id" => 1,
                "kode" => "B01",
                "nilai_banding" => 1,
                "kriteria1" => "C01",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "kode" => "B02",
                "nilai_banding" => 2,
                "kriteria1" => "C01",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 21:49:25",
            ),
            array(
                "id" => 3,
                "kode" => "B03",
                "nilai_banding" => 3,
                "kriteria1" => "C02",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:25:39",
            ),
            array(
                "id" => 4,
                "kode" => "B04",
                "nilai_banding" => 1,
                "kriteria1" => "C02",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "kode" => "B05",
                "nilai_banding" => 1,
                "kriteria1" => "C01",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "kode" => "B06",
                "nilai_banding" => 2,
                "kriteria1" => "C02",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:26:07",
            ),
            array(
                "id" => 7,
                "kode" => "B07",
                "nilai_banding" => 1,
                "kriteria1" => "C03",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "kode" => "B08",
                "nilai_banding" => 3,
                "kriteria1" => "C03",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "kode" => "B09",
                "nilai_banding" => 1,
                "kriteria1" => "C03",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "kode" => "B10",
                "nilai_banding" => 2,
                "kriteria1" => "C01",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:24:53",
            ),
            array(
                "id" => 11,
                "kode" => "B11",
                "nilai_banding" => 5,
                "kriteria1" => "C02",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:25:51",
            ),
            array(
                "id" => 12,
                "kode" => "B12",
                "nilai_banding" => 3,
                "kriteria1" => "C03",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "kode" => "B13",
                "nilai_banding" => 3,
                "kriteria1" => "C04",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "kode" => "B14",
                "nilai_banding" => 2,
                "kriteria1" => "C04",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "kode" => "B15",
                "nilai_banding" => 1,
                "kriteria1" => "C04",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "kode" => "B16",
                "nilai_banding" => 1,
                "kriteria1" => "C04",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "kode" => "B17",
                "nilai_banding" => 1,
                "kriteria1" => "C01",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "kode" => "B18",
                "nilai_banding" => 6,
                "kriteria1" => "C02",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:26:24",
            ),
            array(
                "id" => 19,
                "kode" => "B19",
                "nilai_banding" => 1,
                "kriteria1" => "C03",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "kode" => "B20",
                "nilai_banding" => 6,
                "kriteria1" => "C04",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "kode" => "B21",
                "nilai_banding" => 1,
                "kriteria1" => "C05",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "kode" => "B22",
                "nilai_banding" => 7,
                "kriteria1" => "C05",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "kode" => "B23",
                "nilai_banding" => 1,
                "kriteria1" => "C05",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "kode" => "B24",
                "nilai_banding" => 1,
                "kriteria1" => "C05",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "kode" => "B25",
                "nilai_banding" => 1,
                "kriteria1" => "C05",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "kode" => "B26",
                "nilai_banding" => 5,
                "kriteria1" => "C01",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:25:02",
            ),
            array(
                "id" => 27,
                "kode" => "B27",
                "nilai_banding" => 2,
                "kriteria1" => "C02",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "kode" => "B28",
                "nilai_banding" => 1,
                "kriteria1" => "C03",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "kode" => "B29",
                "nilai_banding" => 5,
                "kriteria1" => "C04",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "kode" => "B30",
                "nilai_banding" => 1,
                "kriteria1" => "C05",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "kode" => "B31",
                "nilai_banding" => 3,
                "kriteria1" => "C06",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "kode" => "B32",
                "nilai_banding" => 2,
                "kriteria1" => "C06",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "kode" => "B33",
                "nilai_banding" => 4,
                "kriteria1" => "C06",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "kode" => "B34",
                "nilai_banding" => 3,
                "kriteria1" => "C06",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "kode" => "B35",
                "nilai_banding" => 3,
                "kriteria1" => "C06",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "kode" => "B36",
                "nilai_banding" => 1,
                "kriteria1" => "C06",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "kode" => "B37",
                "nilai_banding" => 9,
                "kriteria1" => "C01",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:25:11",
            ),
            array(
                "id" => 38,
                "kode" => "B38",
                "nilai_banding" => 4,
                "kriteria1" => "C02",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:26:45",
            ),
            array(
                "id" => 39,
                "kode" => "B39",
                "nilai_banding" => 8,
                "kriteria1" => "C03",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:29:22",
            ),
            array(
                "id" => 40,
                "kode" => "B40",
                "nilai_banding" => 1,
                "kriteria1" => "C04",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "kode" => "B41",
                "nilai_banding" => 1,
                "kriteria1" => "C05",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "kode" => "B42",
                "nilai_banding" => 4,
                "kriteria1" => "C06",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "kode" => "B43",
                "nilai_banding" => 7,
                "kriteria1" => "C07",
                "kriteria2" => "C01",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:25:23",
            ),
            array(
                "id" => 44,
                "kode" => "B44",
                "nilai_banding" => 1,
                "kriteria1" => "C07",
                "kriteria2" => "C02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "kode" => "B45",
                "nilai_banding" => 3,
                "kriteria1" => "C07",
                "kriteria2" => "C03",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 22:29:09",
            ),
            array(
                "id" => 46,
                "kode" => "B46",
                "nilai_banding" => 1,
                "kriteria1" => "C07",
                "kriteria2" => "C04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "kode" => "B47",
                "nilai_banding" => 4,
                "kriteria1" => "C07",
                "kriteria2" => "C05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "kode" => "B48",
                "nilai_banding" => 5,
                "kriteria1" => "C07",
                "kriteria2" => "C06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "kode" => "B49",
                "nilai_banding" => 1,
                "kriteria1" => "C07",
                "kriteria2" => "C07",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );
        NilaiBobotKriteria::insert($nilai_bobot_kriterias);
    }
}
