<?php

namespace Database\Seeders;

use App\Models\NilaiBobotAlternatif;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NilaiBobotAlternatifSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $nilai_bobot_alternatifs = array(
            array(
                "id" => 1,
                "kode" => "NBA01",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "kode" => "NBA01",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "kode" => "NBA01",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "kode" => "NBA01",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "kode" => "NBA02",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "kode" => "NBA02",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "kode" => "NBA02",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "kode" => "NBA02",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "kode" => "NBA03",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "kode" => "NBA03",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "kode" => "NBA03",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "kode" => "NBA03",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "kode" => "NBA04",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "kode" => "NBA04",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "kode" => "NBA04",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "kode" => "NBA04",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "kode" => "NBA05",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "kode" => "NBA05",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "kode" => "NBA05",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "kode" => "NBA05",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "kode" => "NBA06",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "kode" => "NBA06",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "kode" => "NBA06",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "kode" => "NBA06",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "kode" => "NBA06",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "kode" => "NBA07",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "kode" => "NBA07",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "kode" => "NBA07",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "kode" => "NBA07",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "kode" => "NBA07",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "kode" => "NBA08",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "kode" => "NBA08",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "kode" => "NBA08",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "kode" => "NBA08",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "kode" => "NBA08",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "kode" => "NBA09",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "kode" => "NBA09",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 38,
                "kode" => "NBA09",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 39,
                "kode" => "NBA09",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 40,
                "kode" => "NBA09",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "kode" => "NBA10",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "kode" => "NBA10",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "kode" => "NBA10",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "kode" => "NBA10",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "kode" => "NBA10",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 46,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 50,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 51,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 52,
                "kode" => "NBA11",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 53,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 54,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 55,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 56,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 57,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 58,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 59,
                "kode" => "NBA12",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 60,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 61,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 62,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 63,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 64,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 65,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 66,
                "kode" => "NBA13",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 67,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 16:36:53",
            ),
            array(
                "id" => 68,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 69,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 70,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => "2022-12-01 16:36:27",
            ),
            array(
                "id" => 71,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 72,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 73,
                "kode" => "NBA14",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 74,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 75,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 76,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 77,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 78,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 79,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 80,
                "kode" => "NBA15",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 81,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 82,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 83,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 84,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 85,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 86,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 87,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 88,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 89,
                "kode" => "NBA16",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 90,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 91,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 92,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 93,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 94,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 95,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 96,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 97,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 98,
                "kode" => "NBA17",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 99,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 100,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 101,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 102,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 103,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 104,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 105,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 106,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 107,
                "kode" => "NBA18",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 108,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 109,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 110,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 111,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 112,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 113,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 114,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 115,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 116,
                "kode" => "NBA19",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 117,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 118,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 119,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 120,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 121,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 122,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 123,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 124,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 125,
                "kode" => "NBA20",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 126,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 127,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 128,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 129,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 130,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 131,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 132,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 133,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 134,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 135,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 136,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 137,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 138,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 139,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 140,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 141,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 142,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 143,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 144,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 145,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 146,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 147,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 148,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 149,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 150,
                "kode" => "NBA21",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 151,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 152,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 153,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 154,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 155,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 156,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 157,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 158,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 159,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 160,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 161,
                "kode" => "NBA22",
                "kriteria_id" => "C01",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 162,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 163,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 164,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 165,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 166,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 167,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 168,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 169,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 170,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 171,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 172,
                "kode" => "NBA23",
                "kriteria_id" => "C02",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 173,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 174,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 175,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 176,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 177,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 178,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 179,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 180,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 181,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 182,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 183,
                "kode" => "NBA24",
                "kriteria_id" => "C03",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 184,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 185,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 186,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 187,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 188,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 189,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 190,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 191,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 192,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 193,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 194,
                "kode" => "NBA25",
                "kriteria_id" => "C04",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 195,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 196,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 197,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 198,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 199,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 200,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 201,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 202,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 203,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 204,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 205,
                "kode" => "NBA26",
                "kriteria_id" => "C05",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 206,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 207,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 208,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 209,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 210,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 211,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 212,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 213,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 214,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 215,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 216,
                "kode" => "NBA27",
                "kriteria_id" => "C06",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 217,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 218,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 219,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 220,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 221,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 222,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A01",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 223,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 224,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 225,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 226,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 227,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 228,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A02",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 229,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 230,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 231,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 232,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 233,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 234,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A03",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 235,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 236,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 237,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 238,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 239,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 240,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A04",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 241,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 242,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 243,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 244,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 245,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 246,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A05",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 247,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A01",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 248,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A02",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 249,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A03",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 250,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A04",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 251,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A05",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 252,
                "kode" => "NBA28",
                "kriteria_id" => "C07",
                "nilai_banding" => rand(1,9),
                "alternatif1" => "A06",
                "alternatif2" => "A06",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );
        NilaiBobotAlternatif::insert($nilai_bobot_alternatifs);
    }
}
